# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
AUTH_SECRET: "\x7F\xD6\xB5\xC58-\xDD\xE3\xE3\xAF[\xE6\x84\xDE+_\x1Fz?\xF7p\x8C\x03\xDC\x1Cx\x92\xAA\xE4\x9764"
GOOGLE_CLIENT_ID: '376282486981-rq8mp4h46j06t06ejd9hindfjt49flag.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET: 'kMyKDUYEAbd9Ev-GAn3QMaV2'
